config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :books, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  include PgSearch::Model

  pg_search_scope :search_by_title,
    against: [ :title, :description ],
    associated_against: {
      author: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      @books = Book.search_by_title(params[:query])
    else
      @books = Book.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="container">
  <div class="row" style="justify-content:center;">
    <div style="text-align: center;"><h1>BOOKS</h1></div>
    <div style="margin-left: 43%; margin-bottom: 20px; margin-top:10px;">


      <%= form_tag books_path, method: :get do %>
        <%= text_field_tag :query, params[:query],
        placeholder: "Find a book"%>
        <%= submit_tag "Search"%>
      <% end %>


    </div>
    <div style="align-items: center; margin-left: 30%;">
        <% @books.each do |book| %>
        <div id="books" style="max-width: 500px;text-align: center; background-color: pink;border: 1px solid black;border-radius: 5px; margin-bottom: 15px; padding: 20px">
          <h4><strong><%= book.title %></strong> </h4>
          <p>Description: <%= book.description %></p>
          <p>by <%= book.author.first_name %> <%= book.author.last_name %> </p>
          <p><%= book.id %></p>
          </div>
        <% end %>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>